### ISSUE TITLE
Edge case issue

### ISSUE THREAD

**Issue by XhmikosR** [phillipj/metalsmith-yearly-pagination#5]
Initially reported on https://github.com/nodejs/nodejs.org/issues/2422

The current tests cover one similar case, but I think we need a more extended test case. In nodejs.org, we have `blog/index.md`. Maybe this will trigger the issue here too.

PR which works around the problem: https://github.com/nodejs/nodejs.org/pull/2564

**Comment by XhmikosR** [comment]
I think for starters, we need to add one more year in tests.

Secondly, we should have a test with `blog/index.md` instead of `blog.md`. Maybe this will show the error in tests.

**Comment by phillipj** [comment]
Your suggestions sounds like a good start indeed!

It's been too long since I had anything to do with metalsmith, that I don't really have a gut feeling of what might be wrong here at all.

If we were able to re-produce what's happening for nodejs.org with an unit test or two, that would be extremely valuable, both to fix the bug and going forward ofcourse.

**Comment by XhmikosR** [comment]
I'll try to find some time in the next days, but perhaps you could add one more year in tests for starters?

We need to change the `i < 5` check.
